[package]
name = "parser-netwayste"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow  = "1.0.*"
walkdir = "2"

[dependencies.syn]
version = "1.0.56"
features = ["full", "extra-traits"]
