///// matches what's in packet-conwayste.c
#include "config.h"

#include <epan/packet.h>

#define CONWAYSTE_PORT 2016

static int proto_conwayste = -1;


///// matches what's in plugin.c (auto-generated by tools/make-plugin-reg.py in wireshark repo)
///// except for plugin_register definition

#include "config.h"

#include <gmodule.h>

/* plugins are DLLs */
#define WS_BUILD_DLL
#include "ws_symbol_export.h"

#include "epan/proto.h"

//XXX commented these
//void proto_register_conwayste(void);
//void proto_reg_handoff_conwayste(void);

//XXX these probably shouldn't be hardcoded
WS_DLL_PUBLIC_DEF const gchar plugin_version[] = "0.0.1";
WS_DLL_PUBLIC_DEF const int plugin_want_major = 0;
WS_DLL_PUBLIC_DEF const int plugin_want_minor = 0;

//XXX commented this
//WS_DLL_PUBLIC void plugin_register(void);
