///// matches what's in packet-conwayste.c
#include "config.h"

#include <epan/packet.h>

#define CONWAYSTE_PORT 2016

static int proto_conwayste = -1;


///// matches what's in plugin.c (auto-generated by tools/make-plugin-reg.py in wireshark repo)
///// except for plugin_register definition and the consts, which I moved to lib.rs

#include "config.h"

#include <gmodule.h>

/* plugins are DLLs */
#define WS_BUILD_DLL
#include "ws_symbol_export.h"

#include "epan/proto.h"
